// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BibliotecaVirtual.Core.Entidades;

public partial class BibliotecaVirtualContext : DbContext
{
    public BibliotecaVirtualContext(DbContextOptions<BibliotecaVirtualContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Categoria> Categoria { get; set; }

    public virtual DbSet<Emprestimo> Emprestimo { get; set; }

    public virtual DbSet<Livro> Livro { get; set; }

    public virtual DbSet<LivroComentario> LivroComentario { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    public virtual DbSet<UsuarioLivro> UsuarioLivro { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Categoria>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Categori__3214EC0786D02FFD");

            entity.Property(e => e.Nome)
                .HasMaxLength(80)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Emprestimo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Empresti__3214EC0758212B5F");

            entity.HasIndex(e => e.IdUsuario, "Emprestimo_FKIndex1");

            entity.HasIndex(e => e.IdLivro, "Emprestimo_FKIndex2");

            entity.Property(e => e.DataDevolucao).HasPrecision(0);
            entity.Property(e => e.DataEmprestimo).HasPrecision(0);

            entity.HasOne(d => d.IdLivroNavigation).WithMany(p => p.Emprestimo)
                .HasForeignKey(d => d.IdLivro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Emprestim__IdLiv__4BAC3F29");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.Emprestimo)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Emprestim__IdUsu__4AB81AF0");
        });

        modelBuilder.Entity<Livro>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Livro__3214EC07550DE556");

            entity.HasIndex(e => e.IdCategoria, "Livro_FKIndex2");

            entity.Property(e => e.AnoPublicacao).HasPrecision(0);
            entity.Property(e => e.Autor)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CriadoEm).HasPrecision(0);
            entity.Property(e => e.Descricao)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Titulo)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.IdCategoriaNavigation).WithMany(p => p.Livro)
                .HasForeignKey(d => d.IdCategoria)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Livro__IdCategor__3E52440B");
        });

        modelBuilder.Entity<LivroComentario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LivroCom__3214EC074062F61B");

            entity.HasIndex(e => e.IdLivro, "LivroComentario_FKIndex1");

            entity.HasIndex(e => e.IdUsuario, "LivroComentario_FKIndex2");

            entity.Property(e => e.Conteudo)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.CriadoEm).HasPrecision(0);

            entity.HasOne(d => d.IdLivroNavigation).WithMany(p => p.LivroComentario)
                .HasForeignKey(d => d.IdLivro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LivroCome__IdLiv__5165187F");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.LivroComentario)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LivroCome__IdUsu__52593CB8");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Usuario__3214EC0705B7BEB7");

            entity.Property(e => e.DataNasc).HasPrecision(0);
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.NomeCompleto)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Papel)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Senha)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<UsuarioLivro>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UsuarioL__3214EC07E120A60F");

            entity.HasIndex(e => e.IdUsuario, "UsuarioLivro_FKIndex1");

            entity.HasIndex(e => e.IdLivro, "UsuarioLivro_FKIndex2");

            entity.HasOne(d => d.IdLivroNavigation).WithMany(p => p.UsuarioLivro)
                .HasForeignKey(d => d.IdLivro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UsuarioLi__IdLiv__44FF419A");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.UsuarioLivro)
                .HasForeignKey(d => d.IdUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UsuarioLi__IdUsu__440B1D61");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}