// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BibliotecaVirtual.Core.Entidades;

public partial class Emprestimo
{
    public Emprestimo(int idLivro, int idUsuario, DateTime dataEmprestimo, DateTime dataDevolucao)
    {
        IdLivro = idLivro;
        IdUsuario = idUsuario;
        DataEmprestimo = DateTime.Now;
        DataDevolucao = dataDevolucao;
    }

    public int Id { get; set; }

    public int IdLivro { get; set; }

    public int IdUsuario { get; set; }

    public DateTime DataEmprestimo { get; set; }

    public DateTime DataDevolucao { get; set; }

    public virtual Livro IdLivroNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}