// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using BibliotecaVirtual.Core.Enums;

namespace BibliotecaVirtual.Core.Entidades;

public partial class Livro
{
    public Livro(int idCategoria, string titulo, string autor, DateTime? anoPublicacao, string descricao)
    {
        IdCategoria = idCategoria;
        Titulo = titulo;
        Autor = autor;
        AnoPublicacao = anoPublicacao;
        CriadoEm = DateTime.Now;
        Descricao = descricao;
    }

    public int Id { get; set; }

    public int IdCategoria { get; set; }

    public string Titulo { get; set; }

    public string Autor { get; set; }

    public DateTime? AnoPublicacao { get; set; }

    public DateTime? CriadoEm { get; set; }

    public string Descricao { get; set; }

    public StatusLeituraEnum StatusLeitura { get; set; }

    public virtual Categoria IdCategoriaNavigation { get; set; }

    public virtual ICollection<LivroComentario> LivroComentario { get; set; } = new List<LivroComentario>();

    public virtual ICollection<UsuarioLivro> UsuarioLivro { get; set; } = new List<UsuarioLivro>();

    public void Lido()
    {
        if(StatusLeitura == StatusLeituraEnum.EmAndamento || StatusLeitura == StatusLeituraEnum.Iniciado)
        {
            StatusLeitura = StatusLeituraEnum.Lido;
        }
    }
    public void Update(string titulo, string autor, DateTime? anoPublicacao, string descricao)
    {
        Titulo = titulo;
        Autor = autor;
        AnoPublicacao = anoPublicacao;
        Descricao = descricao;
    }
}