// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace BibliotecaVirtual.Core.Entidades;

public partial class UsuarioLivro
{
    public UsuarioLivro(int idLivro, int idUsuario)
    {
        IdLivro = idLivro;
        IdUsuario = idUsuario;
    }

    public int Id { get; set; }

    public int IdLivro { get; set; }

    public int IdUsuario { get; set; }

    public virtual Livro IdLivroNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}