// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BibliotecaVirtual.Core.Entidades;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BibliotecaVirtual.Core.Entidades.Configurations
{
    public partial class CategoriaConfiguration : IEntityTypeConfiguration<Categoria>
    {
        public void Configure(EntityTypeBuilder<Categoria> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Categori__3214EC0707B37D1C");

            entity.Property(e => e.Nome)
            .HasMaxLength(80)
            .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Categoria> entity);
    }
}
