// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BibliotecaVirtual.Core.Entidades;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BibliotecaVirtual.Core.Entidades.Configurations
{
    public partial class LivroConfiguration : IEntityTypeConfiguration<Livro>
    {
        public void Configure(EntityTypeBuilder<Livro> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Livro__3214EC07708D9772");

            entity.HasIndex(e => e.IdCategoria, "Livro_FKIndex2");

            entity.Property(e => e.AnoPublicacao).HasPrecision(0);
            entity.Property(e => e.Autor)
            .HasMaxLength(100)
            .IsUnicode(false);
            entity.Property(e => e.CriadoEm).HasPrecision(0);
            entity.Property(e => e.Descricao)
            .HasMaxLength(100)
            .IsUnicode(false);
            entity.Property(e => e.Titulo)
            .HasMaxLength(100)
            .IsUnicode(false);

            entity.HasOne(d => d.IdCategoriaNavigation).WithMany(p => p.Livro)
            .HasForeignKey(d => d.IdCategoria)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__Livro__IdCategor__3E52440B");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Livro> entity);
    }
}
