// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BibliotecaVirtual.Core.Entidades;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BibliotecaVirtual.Core.Entidades.Configurations
{
    public partial class LivroComentarioConfiguration : IEntityTypeConfiguration<LivroComentario>
    {
        public void Configure(EntityTypeBuilder<LivroComentario> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__LivroCom__3214EC07F290574F");

            entity.HasIndex(e => e.IdLivro, "LivroComentario_FKIndex1");

            entity.HasIndex(e => e.IdUsuario, "LivroComentario_FKIndex2");

            entity.Property(e => e.Conteudo)
            .HasMaxLength(200)
            .IsUnicode(false);
            entity.Property(e => e.CriadoEm).HasPrecision(0);

            entity.HasOne(d => d.IdLivroNavigation).WithMany(p => p.LivroComentario)
            .HasForeignKey(d => d.IdLivro)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__LivroCome__IdLiv__4AB81AF0");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.LivroComentario)
            .HasForeignKey(d => d.IdUsuario)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__LivroCome__IdUsu__4BAC3F29");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LivroComentario> entity);
    }
}
