// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BibliotecaVirtual.Core.Entidades;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BibliotecaVirtual.Core.Entidades.Configurations
{
    public partial class UsuarioLivroConfiguration : IEntityTypeConfiguration<UsuarioLivro>
    {
        public void Configure(EntityTypeBuilder<UsuarioLivro> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__UsuarioL__3214EC077EA5EDBF");

            entity.HasIndex(e => e.IdUsuario, "UsuarioLivro_FKIndex1");

            entity.HasIndex(e => e.IdLivro, "UsuarioLivro_FKIndex2");

            entity.HasOne(d => d.IdLivroNavigation).WithMany(p => p.UsuarioLivro)
            .HasForeignKey(d => d.IdLivro)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__UsuarioLi__IdLiv__44FF419A");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.UsuarioLivro)
            .HasForeignKey(d => d.IdUsuario)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK__UsuarioLi__IdUsu__440B1D61");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UsuarioLivro> entity);
    }
}
